### ISSUE TITLE
Support Directory.Build.props

### ISSUE THREAD

**Issue by adamralph** [jerriep/dotnet-outdated#104]
Currently, if a package is referenced in `Directory.Build.props`, `dotnet-outdated` does not analyse it.

**Comment by jerriep** [comment]
@adamralph I created a test project to try this out and it works for me.

Here is the sample project I used:
https://github.com/jerriep/dotnet-outdated/tree/master/test-projects/build-props

As you can see from the screenshot below, **dotnet-outdated** does indeed analyse it and report it as outdated:
![image](https://user-images.githubusercontent.com/1006420/47946315-a5f30880-df3c-11e8-9ff1-ff0f3e7d0f7d.png)

Can you provide me with more information on your particular scenario where it fails? 

An actual `.csproj` and `Directory.Build.props` which replicates the issue you experience will be helpful.

**Comment by adamralph** [comment]
@jerriep you should be able to reproduce the problem by running `dotnet-outdated` on this commit: https://github.com/xbehave/xbehave.net/commit/58a4f8437409338ac3fe1a6d9492bd5d7ae7ae9e

You can see that `MinVer` version `1.0.0-alpha.9` is referenced: https://github.com/xbehave/xbehave.net/blob/58a4f8437409338ac3fe1a6d9492bd5d7ae7ae9e/src/Directory.Build.props#L5

But `1.0.0-alpha.10` is available: https://www.nuget.org/packages/MinVer/1.0.0-alpha.10

<img src="https://user-images.githubusercontent.com/677704/47950706-4a357900-df56-11e8-88e5-99fc260fe8a9.png" width="643px" />

Just as a sanity check, if I run `dotnet-outdated` on other projects, the new version of MinVer is detected:

<img src="https://user-images.githubusercontent.com/677704/47950736-c760ee00-df56-11e8-8c4e-fbbbff81c02e.png" width="314px" />

**Comment by jerriep** [comment]
Hmm, interesting. With the latest version of **dotnet-outdated**, I get the following result:
![image](https://user-images.githubusercontent.com/1006420/47958955-2848fe80-e009-11e8-83ef-48e679398a58.png)

So, it is able to handle `Directory.Build.props` correctly, since it is aware of the existence of the `MinVer` package, but for some or other reason there is an error when it is trying to resolve the latest version.

I believe it is related to [this issue](https://github.com/jerriep/dotnet-outdated/issues/96#issuecomment-433848369) which is on my radar to look into. Will see what I can find out...

**Comment by jerriep** [comment]
@adamralph The underlying problem is the `MinVer` package is targeting .NET Standard 2.0 while the XBehave.Core project is targeting .NET Standard 1.1. However, the `MinVer` packages is marked as a Development Dependency:

![image](https://user-images.githubusercontent.com/1006420/47961523-43cefc00-e03f-11e8-88aa-b67ae7b041fb.png)

So I should be able to ignore the target framework for this package since it is irrelevant.

Previously when I ran into this issue was with Roslyn Analyzers. At the time what appeared to make them different was that they contained no dependency sets, so I added some code to allow for this special case:
https://github.com/jerriep/dotnet-outdated/commit/9eedfe464d2097aa3065ef692895dc2afd534f54

Now, it turns out that that was a half-baked solution on my side since the correct solution should have been to check whether a package is a development dependency and in that case ignore the target framework requirements.

The only problem is that the NuGet `PackageMetadataResource` does not tell me whether a package is a development dependency, so I am not quite sure how I will be able to do this check. I need to explore more, but at this stage, I am not sure how to fix this one for you 😞

**Comment by adamralph** [comment]
@jerriep I guess you are figuring out which platforms a package depends on based on the dependency groups? The problem is, they are not reliable. All they are saying is "for platform X, I have dependencies Y". If you look inside the MinVer package, it doesn't actually ship anything platform specific, since it's just a targets file and some supporting binaries. In order to truly work out the platform support, I think you have to look into the folder structure and look for TFM folders under `build`, `lib`, `tools`, etc. Some packages, such as MinVer may have none of those, in which case they support _all_ platforms.

BTW I acknowledge that MinVer shouldn't specify that dependency group. I own that package, and unfortunately I haven't found a way to suppress that when creating that package by packing against the csproj. However, tooling should still not be using the dependency group as a means to determine platform support. It is the TFM folders (or lack of them) that indicates platform support. For example, I can install MinVer into a .NET Core 1.1. project in Visual Studio without problem.

**Comment by jerriep** [comment]
@adamralph Yeah, in cases where there were no TFM it worked fine, which was how I had this solved previously. In your case the fact that the package specified a TFM was what threw a bit of a curve ball.

In any case, it appears that I can look at the `DevelopmentDependency` node in the `.nuspec` file as this appears to be the most reliable thing so far. Running the latest (beta) version on your project gives the following result:

![image](https://user-images.githubusercontent.com/1006420/47964438-c3bf8b00-e06c-11e8-936b-4fb8b18a9f89.png)

The issue with `LiteGuard*` appears to be that you are referencing newer versions either from a private feed or perhaps they are unlisted packages?

Not sure when I'll release the latest version since I want to do some more code cleanup and will likely only get to it next weekend.

For now, if you want to test this latest version, you can uninstall your current version and then install the prerelease using the following command:

```bash
dotnet tool install -g dotnet-outdated --version 2.2.0-pre.191 --add-source https://www.myget.org/F/jerriep/api/v3/index.json
```
