### ISSUE TITLE
Performance-Improvements

### ISSUE THREAD

**Issue by batzen** [jerriep/dotnet-outdated#143]
Hi there,
i love this tool, but IMHO it takes way too long to analyze/list the outdated dependencies.
Even for my small project (3 project files, 2 frameworks and a few dozen dependencies) it takes 1 minute and 7 seconds to run (on my machine).
I had a look at the source code of this tool and was able to get this time down to 11 seconds.
The performance benefits from my changes should be even larger for larger solutions.
Do you know of any larger OSS projects i could test this on?

My question now is: Would you be interested in me going forward with this and create a WIP PR and discuss my changes there?
I am asking this because i want to make sure you are not currently working on something like that and because i prefer, in my own OSS projects, to be asked in advance about such PRs.

**Comment by jerriep** [comment]
@batzen I am actually not giving much attention to this anymore - so much so that just yesterday I was looking for a way to mark this project as inactive. The reasons for this are twofold:

1. I am now 100% focused on my own company I am trying to get off the ground and do not have time for much else
2. A lot of what this tool does can now be done by the built-in `dotnet list package --outdated` command.

You are welcome to open a PR, but it may take a long time to get a decent reaction to it from me. So, if you are willing to live with that, you can go ahead

**Comment by ad-mca-mk** [comment]
@batzen are you interested in providing a PR for the performance improvements you described?

**Comment by batzen** [comment]
Will try to prepare a PR for this.

**Comment by jerriep** [comment]
v2.10.0 has been pushed to NuGet with these changes. This is a MASSIVE speed improvement. Thanks again @batzen
