### ISSUE TITLE
Option to only show outdated packages

### ISSUE THREAD

**Issue by PaitoAnderson** [jerriep/dotnet-outdated#16]
An option to only show outdated packages might be nice, just like `npm outdated`.

**Comment by jerriep** [comment]
Yes, this will be useful. Thanks for the suggestion.

**Comment by anangaur** [comment]
I think that should be the default :) btw, https://github.com/NuGet/Home/issues/5762 is `up for grabs` :-)

**Comment by jerriep** [comment]
@anangaur Yes, in hindsight it would have been better for it to be the default. However, I am reluctant to change the default behaviour now. What I am considering is adding some sort of settings file to allow developers to override default settings.

Regarding that other issue: I have already developed this tool. I have no intention of doing it twice. Also, here I can decide where I want to take the tool. Over there I am beholden to MS's vision for what the command should or should not do.

**Comment by thomaslevesque** [comment]
I just gave this a try, and it's harder than I imagined. The difficulty comes from the fact that `dotnet-outdated` writes what it does as it's doing it. So the name of the package is displayed before actually checking if it's up-to-date. So if it's up-to-date, the line needs to be deleted. So far so good, and it works fine.

Problems start to happen when the `--transitive` option is set. In this case, we need to display a package if one of its dependencies is outdated. For instance, if we have a package A with dependencies B and C, we need to do this:
- display A
- display B, check if it's outdated, delete the line if it's not
- display C, check if it's outdated, delete the line if it's not
- if A, B and C are all up-to-date, delete the line for A

The problem is that we're no longer on the line for A, we're on the next line. We can change `Console.CursorTop` to go back to that line; it works in the default Windows console, but not necessarily in other terminals. For instance, in ConEmu, it has no effect, so the line is not deleted.

I don't see a way around this. The solution might be to not display the progression when the option to show only outdated packages is enabled.

@jerriep would you be interested in a WIP PR with what I've done so far?

**Comment by thomaslevesque** [comment]
(in fact, I can no longer reproduce the issue with ConEmu, so my solution seems to be working... probably needs more tests, though)

**Comment by jerriep** [comment]
@thomaslevesque I want to handle this and #6 at the same time. 

My idea was to not display the individual progress as each assembly is scanned. Just simply display a generic "Busy checking dependencies..." status message. Then at the end, after the process was completed, to just display the list with the summary of outdated packages. 

The reason I want to do this is that I want to display the report a little bit differently. I want to group the outdated packages by the package, instead of by project. I think it would make more sense to the user if we tell them "here are the packages that are outdated, and for each package here are the projects which are affected".

Does that make sense?

Once this is in place it should be fairly easy to build #6 on top of that by just prompting after each package whether the user wants to update the package or not.

**Comment by thomaslevesque** [comment]
@jerriep, it totally makes sense, and would remove the problem I was having.

**Comment by jerriep** [comment]
Cool. If you want to put something like that together, I would be interested in the PR ;)

Don't worry about the part in #6, if you can just do the work described in this issue it would be good for now.

**Comment by jerriep** [comment]
Also, in hindsight I think I must eat humble-pie and admit that @anangaur was correct in stating that this should be the default. The current output can become quite difficult to comprehend - especially when you have a solution with many projects or if you are scanning transitive dependencies.

All the developer is really interested in is to know which packages are outdated and which projects are affected by that. The current way I display the information makes that difficult to comprehend.

**Comment by thomaslevesque** [comment]
> If you want to put something like that together, I would be interested in the PR ;)

Do you mean grouping by package instead of by project? Or just the "Busy checking dependencies" part?

**Comment by jerriep** [comment]
Basically to just print out a summary at the end which displays just the outdated packages. And for each package, underneath the package name, displays the projects which are affected.

But this can become tricky, because different projects can reference different versions of the package. 

Newtonsoft.Json - v11.0.3 available
- DotNetOutdated (referencing v10.0.3)
- DotNetOutdated.Tests (referencing v10.0.3)
LibGit2Sharp - v0.25.0 available
- DotNetOutdated (referencing v0.24.0)
System.IO.Abstractions - v2.1.0.178 available
- DotNetOutdated (referencing v2.0.0.128)
- DotNetOutdated.Tests (referencing v2.1.0.155)

What makes this even more tricky is that different target frameworks in the same project can be referencing different versions (see #20). 

So maybe a bit more thought needs to go into what the final output should look like before one starts coding away.

**Comment by thomaslevesque** [comment]
> What makes this even more tricky is that different target frameworks in the same project can be referencing different versions

Well, we could display the results like this:

```
Newtonsoft.Json - v11.0.3 available
- MyLibrary [.NETStandard,Version=v2.0] (referencing v10.0.3)
- MyLibrary [.NETFramework,Version=v4.5] (referencing v10.0.3)
- MyLibrary.Tests [.NETCoreApp,Version=v2.1] (referencing v10.0.3)
- MyLibrary.Tests [.NETFramework,Version=v4.5] (referencing v10.0.3)
```

**Comment by jerriep** [comment]
One more twist is that different latest versions may be applicable for the different target frameworks, e.g.

![image](https://user-images.githubusercontent.com/1006420/42380563-8e33343c-8158-11e8-9e38-661baf967b21.png)

So in this case, the latest version for .NET Standard 1.6 is v1.1.2, but for .NET Standard 2.0, the latest version is v2.1.1. 

So the following may make more sense for the summary:

```
Newtonsoft.Json
- MyLibrary [.NETStandard,Version=v2.0] - v2.1.1 (currently referencing v2.1.0)
- MyLibrary [.NETStandard, Version=v1.6] - v1.1.2 (currently referencing v1.1.1)
```

**Comment by jerriep** [comment]
@thomaslevesque Any luck with this one?

I did a commit today to fix some output redirection issues. Please ensure you do a rebase please.

**Comment by thomaslevesque** [comment]
@jerriep I haven't found time to really work on it yet.

I have a question, though: in the proposed output format, how would transitive dependencies be shown?

**Comment by jerriep** [comment]
@thomaslevesque If you haven't started, mind if I pick it up instead? I have time on my hands atm and can get going with this

Yes, for transitive dependencies we should have some sort of indicator. Maybe a [T] or something like that after the package name.

**Comment by thomaslevesque** [comment]
@jerriep sure, go ahead!

**Comment by jerriep** [comment]
Version 2.0.0 is now available on NuGet which resolves this issue:
https://www.nuget.org/packages/dotnet-outdated/2.0.0

**Comment by thomaslevesque** [comment]
@jerriep thanks, very nice!
Just one thing, though: maybe projects with no outdated dependencies shouldn't be shown at all?

**Comment by jerriep** [comment]
Yeah, that's possible, I suppose. Though for me, personally, I find it better to see the project name listed with "no outdated dependencies", so I can be sure it was actually processed

**Comment by thomaslevesque** [comment]
Fair enough!
