### ISSUE TITLE
Attribute value casing is changed during update

### ISSUE THREAD

**Issue by adamralph** [jerriep/dotnet-outdated#59]
E.g. this is after running `dotnet-outdated.exe -u`.

![image](https://user-images.githubusercontent.com/677704/44958992-42bb0a80-aee8-11e8-928a-191eb3319047.png)

**Comment by jerriep** [comment]
I simply run the `dotnet add package` command, so the .NET CLI is changing your project files, not dotnet-outdated itself.

https://github.com/jerriep/dotnet-outdated/blob/e155c3e27d29e17d8dc0572f932fe405119e6cc0/src/DotNetOutdated/Services/DotNetAddPackageService.cs#L21

What happens when you run the `dotnet add package` command directly? Does that change the casing as well?

**Comment by adamralph** [comment]
@jerriep when I run `dotnet add package`, I get exactly the same behaviour. I'll send a PR to the FAQ so that you can avoid this question in the future. 😄 

Thanks.
