### ISSUE TITLE
Project files are reformatted during update

### ISSUE THREAD

**Issue by adamralph** [jerriep/dotnet-outdated#60]
E.g. this is after running `dotnet-outdated.exe -u`.

![image](https://user-images.githubusercontent.com/677704/44959009-75fd9980-aee8-11e8-8256-56c7c18891e6.png)

**Comment by jerriep** [comment]
I simply run the `dotnet add package` command, so the .NET CLI is changing your project files, not dotnet-outdated itself.

https://github.com/jerriep/dotnet-outdated/blob/e155c3e27d29e17d8dc0572f932fe405119e6cc0/src/DotNetOutdated/Services/DotNetAddPackageService.cs#L21

What happens when you run the `dotnet add package` command directly? Does that reformat your project files?

**Comment by adamralph** [comment]
See https://github.com/jerriep/dotnet-outdated/issues/59#issuecomment-418050800
