### ISSUE TITLE
Request: remove old packages

### ISSUE THREAD

**Issue by lonix1** [jerriep/dotnet-outdated#63]
New user here. I'm not sure if this is within this tool's scope.

I see that in addition to reporting outdated packages, this tool also does updates.

So it would be nice to have a "remove obsolete packages" option, to clear the project's nuget cache of old packages that were just updated. (In fact to clear all packages which are not referenced by `.csproj` files)

**Comment by jerriep** [comment]
Have you actually tested this on a project? Because AFAIK, when using the new csproj file format, the NuGet packages are not placed in the project folder anymore but in a global folder:
https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

Also, I just use the normal .NET CLI under the hood, and to my knowledge, there is no way for the .NET CLI (or the NuGet CLI) to do this. This is not something I have any intention of handling myself, so unless the .NET Core CLI does this out of the box, this is not something which dotnet-outdated will provide.

**Comment by jerriep** [comment]
Yeah, and since they are global to **all** projects, there is no sure way for the NuGet tooling to delete them because if one project does not reference a particular version anymore, it does not mean that there is not another project on your computer which still references that version.

In any case, this is not something this tool will take care of for you and it is [also not something which the NuGet tooling will do for you](https://developercommunity.visualstudio.com/content/problem/62591/removing-nuget-packages-does-not-remove-from-packa.html).

If you want to clear that folder you can take the steps described on [this page](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders).

**Comment by thoemmi** [comment]
Some time ago I wrote a PowerShell script removing packages from the cache which haven't been touched for a configurable time: https://thomasfreudenberg.com/archive/2017/04/21/cleaning-nugets-cache/

**Comment by lonix1** [comment]
@jerriep Yep that makes it harder to determine what's really outdated... I think this was a poor design choice on their part. npm doesn't work this way. On an SSD that directory becomes expensive.
@thoemmi Nice script, I'll do something similar in bash.
